Features.md : Updated
RajuKoushik/traveldiaries-server pull request #14
Opened 2017-03-30 19:40 UTC by chetanya-shrimali

Added further features.

2017-03-30 19:47 UTC, yashLadha requested changes

2017-03-30 19:47 UTC, yashLadha commented on Features.md
> +   * Current_Date
In place of current date it would be better if you use a specific date, whether or not Current date ? what do u think @RajuKoushik

2017-03-30 19:47 UTC, yashLadha commented on Features.md
> +    * Dname
It is already a implemented Feature. Have a look at it

2017-03-30 19:50 UTC, yashLadha requested changes
Please see comments. Ping me after changes :+1:

2017-03-30 19:50 UTC, yashLadha commented on Features.md
> +    * Diary Destination
They are already implemented have a look at it. `diary_brief = models.CharField(max_length=300)
diary_string = models.CharField(max_length=1000,null=True)`

2017-03-30 20:03 UTC, RajuKoushik requested changes

2017-03-30 20:03 UTC, RajuKoushik commented on Features.md
> -   * User Travel Histroy (the places the user has been to)
We have to maintain the travel history of the user so User Travel History should be there.

2017-03-30 20:04 UTC, RajuKoushik commented on Features.md
> +   * Current_Date
What are the pros of saving the Current date  ? Any motive behind it.

2017-03-30 20:19 UTC, chetanya-shrimali commented
@RajuKoushik  @yashLadha Please review it.

2017-03-31 06:15 UTC, yashLadha commented
@chetanya-shrimali @RajuKoushik  We can also add a reminder counter for a trip planned in the log. What do u think?

2017-03-31 06:46 UTC, chetanya-shrimali commented
i think we should add a separate table for reminder.
Which will include all types of reminders like trip date reminder, post reminder (if location changes) etc.

2017-03-31 06:49 UTC, yashLadha commented
GFI, append necessary changes in the PR. :+1:  @RajuKoushik  need opinion

2017-03-31 15:16 UTC, chetanya-shrimali commented
@RajuKoushik Please review it. so i can work on different issue

2017-04-01 09:09 UTC, merged

2017-04-01 09:10 UTC, RajuKoushik commented
Merged !!